name = "NautyGraphs"
uuid = "7509a0a4-015a-4167-b44b-0799a1a2605e"
authors = ["Maximilian HUEBL <maximilian.huebl@ist.ac.at>"]
version = "0.6.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
nauty_jll = "55c6dc9b-343a-50ca-8ff2-b71adb3733d5"

[compat]
Graphs = "1.9"
LinearAlgebra = "1"
SHA = "0.7, 1"
julia = "1.6"
nauty_jll = "2.8.9"
